Repository homeport/build-load, pull requests merged in 2021-09, with the labels that each got.

#74 Bump Go version to `1.16`
  .github/workflows/build.yml
  .github/workflows/release.yml
  go.mod
Labels: enhancement, dependencies

#73 Add dockerfile to strategy list
  internal/load/models.go
Labels: enhancement

#75 Bump Go modules
  .github/dependabot.yml
  go.mod
  go.sum
Labels: dependencies

#76 Migrate to Go JWT version 4
  go.mod
  go.sum
  internal/load/images.go
Labels: dependencies
